Data Type in Numpy

i - integer   //
b -boolean  //
u - unsigned integer  //
f - float  //
c - complex float  //
m - timedelta  //
M - datetime  //
O - object  //
s - string  //
U - unicode string  //
v - fixed chunk of memory for other type(void)

Checking the data type of an array

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.dtype)               # int32

ModuleNotFoundError: No module named 'numpy'

In [ ]:
import numpy as np
arr=(['animal','bat','cat'])
print(arr.dtype)             #<U7

ModuleNotFoundError: No module named 'numpy'

Creating array with a defined data type

In [3]:
arr= np.array([1,2,3,4,5],dtype='s')
print(arr)
print(arr.dtype)         #[b'1' b'2' b'3' b'4']
                         #[s1]

NameError: name 'np' is not defined

Creating an array with data types 4 bytes integer

In [4]:
arr= np.array([1,2,3,4,5],dtype='i4')
print(arr)
print(arr.dtype)          #[1 2 3 4]
                          #int32

NameError: name 'np' is not defined

Numpy array Shape

the shape of an array is the number of elements in each dimension 

Print the shape of 2D array

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)           #(2,5)

ModuleNotFoundError: No module named 'numpy'

In [ ]:
import numpy as np
arr=np.array([[[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5]]])
print(arr.shape)             #(1,3,5)

Joining numpy array

In [7]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1 , arr2))
print(arr)

NameError: name 'np' is not defined

Join 2d array


In [ ]:
arr1=np.array([[1,2,3],[7,8,9]])
arr2=np.array([[4,5,6],[10,11,12]])
arr=np.concatenate((arr1 , arr2),axis=1)
print(arr)   
                 #  [[1 2 3 4 5 6]
                 #  [7 8 9 10 11 12]]

In [ ]:
arr1=np.array([[1,2,3],[7,8,9]])
arr2=np.array([[4,5,6],[10,11,12]])
arr=np.concatenate((arr1 , arr2),axis=0)
print(arr)
                #  [[1 2 3]
                #  [7 8 9]
                #  [4 5 6]
                #  [10 11 12]]

Spliting numpy array

Spliting the array in three parts

In [ ]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)       
              # [array([1,2]),array([3,4]),array([5,6])]

NameError: name 'np' is not defined

Spliting the array in four parts

In [9]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)       
              # [array([1,2]),array([3,4]),array([5]),array([6])]

NameError: name 'np' is not defined

Ravel and flatten

convert multidimensional array into 1D array

In [ ]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
n=m.ravel()
print(n)

                       #    [1 2 3 4 5 6 7 8 9]

In [10]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
n=m.flatten()
print(n)

                       #    [1 2 3 4 5 6 7 8 9]

NameError: name 'np' is not defined

In [11]:
c=np.array([[[[1,2,3],[4,54,45],[33,354,65]]]])
print(c)
print(c.ndim)
d=c.ravel()
print(d)
print("now the new dimension is ",d.ndim)

NameError: name 'np' is not defined

Unique function

In [ ]:
k=np.array([22,43,67,2,22,65,34,75,43,23,22])
print(k)
x=np.unique(k)
print(x)

        #   [22 43 67 2 22 65 34 75 43 23 22]
        #   [22 43 67 2 65 34 75 43 23]

In [ ]:
k=np.array([22,43,67,2,22,65,34,75,43,23,22])
print(k)
x=np.unique(k,return_index=True)
print(x)

In [ ]:
k=np.array([22,43,67,2,22,65,34,75,43,23,22])
print(k)
x=np.unique(k,return_index=True , return_counts = True)
print(x)

Delete

In [ ]:
k=np.array([22,43,67,2,65,34,75,43,23])
d=np.delete(a,[1])
print(d)  
        #   [22 67 2 65 34 75 43 23]

In [12]:
c=np.array([[[1,2,3],[4,54,45],[33,354,65]]])
print(c)
d=np.delete(c,1,axis=0)
print(d)

NameError: name 'np' is not defined